import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar/Sidebar";
import Header from "@/components/Header/Header";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#E6E6ED]`}>
				<div className="flex gap-4 p-4 h-screen overflow-hidden">
					<div>
						<Sidebar />
					</div>

					<div className="flex-1 flex flex-col">
						<Header />
						<main className="flex-1 overflow-auto mt-4 flex flex-col">{children}</main>
					</div>
				</div>
			</body>
		</html>
	);
}
