import type { Metadata } from "next";
import { Geist, Geist_Mono, DM_Sans } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const dmSans = DM_Sans({
	weight: ["400"],
	subsets: ["latin"],
	variable: "--dm-sans",
});

export const metadata: Metadata = {
<<<<<<< HEAD
	title: "Create Next App",
	description: "Generated by create next app",
=======
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
>>>>>>> main
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
<<<<<<< HEAD
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} ${dmSans.variable} antialiased`}>
				<div className="ellipse1"></div>
				{children}
				<div className="ellipse2"></div>
			</body>
		</html>
	);
=======
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
>>>>>>> main
}
